### ISSUE TITLE
Model intake

### ISSUE THREAD

**Issue by TheMadBevah** [GeroVanMi/algorithmic-quartet-mlops#6]
Possibilities:
- Get model from weights and biases, and get model directly. The Tag is deployment
- This happens over GitHub Actions.

**Comment by GeroVanMi** [comment]
I am not sure yet if the server will pull the deployed model whenever it starts (i.e. we only need to re-start the server to update it) or whether the model needs to be bundled alongside the server (i.e. we need to re-deploy the server to update). 

This will depend on the specific implementation, so if you can, try to pull the model from W&B whenever the server starts (or even upon request?) so that we don't need to re-deploy the server everytime there is a new model. 
However, this will mean decreased performance, so if performance is an issue, maybe we'll need to change this.

**Comment by TheMadBevah** [comment]
It does pull the newest on startup of the server. Due to it being down usually, it should have the newest one available.
